# A first workflow to play around with the editor
  name: My First Workflow
  on:
    push:
      branches:
        - main
    workflow_dispatch:
  jobs:
    first_job:
      name: My first jobs:
      runs-on: ubuntu-latest
      steps:
        - name: Greet the user
        - run: |
            echo "Hello world 🌏🤗 from ${{github.actor}}."
            echo "current branch is '${{ github.ref }}'."
        - name: Checkout
          uses: actions/checkout@v6.1.0
        - run: tree 
