# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  first_job:
    name: My first jobs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET}} 🌏🤗 from ${{github.actor}}."
          echo "current branch is '${{ github.ref }}'."
          echo "My secret is '${{ secrets.MY_SECRET }}'. "
      - name: Checkout
        uses: actions/checkout@v6.1.0
      - run: tree
  Test:
    name: Test
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET}} 🌏🤗 from ${{github.actor}}."
          echo "current branch is '${{ github.ref }}'."
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is '${sec}'. "
  
  Load-Test:
    name: Load-Test
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: first_job
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET}} 🌏🤗 from ${{github.actor}}."
          echo "current branch is '${{ github.ref }}'."
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is '${sec}'. "
  Production:
    name: Production
    runs-on: ubuntu-latest
    needs: [Test, Load-Test] 
    environment:
      name: Production
      url: https://sg.finance.yahoo.com
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET}} 🌏🤗 from ${{github.actor}}."
          echo "current branch is '${{ github.ref }}'."
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is '${sec}'. "